### ISSUE TITLE
Search algorithm & Episode title

### ISSUE THREAD

**Issue by flawsom** [gneiru/anirohi#119]
it only works for the japaneese names ,

try searching something like " solo levelling ", and it would show no results!!

Instead of showing the episode title it's showing the anime name and number...
also ig aniwatch api has much more animes and functiunality, let me know if i can help

**Comment by gneiru** [comment]
You are right, the 3rd party api I am using is not aniwatch which doesn't display the episode title. While migrating to aniwatch is a good idea, their slugs doesn't match, i.e. the slug of solo leveling in aniwatch is "solo-leveling-18718" while here it's "ore-dake-level-up-na-ken" and it might cause conflicts for watchlists and notifications. I hope you understand, thanks.

> Instead of showing the episode title it's showing the anime name and number... also ig aniwatch api has much more animes and functiunality, let me know if i can help

**Comment by flawsom** [comment]
Also ig the player could recieve some improvements aswell
like u just used a default one with nothing special

how about integrating art player or vydia or something more of your own costumisation that stands out


also as one more improvement we can add the ability to download the same thing aswell ( the seleceted ep - it's there in consumet for vid src and gogo and more )



these things ig can be implemented in the kdrama web app aswell
