### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by flawsom** [gneiru/anirohi#121]
Also ig the player could recieve some improvements aswell
like u just used a default one with nothing special

how about integrating art player or vydia or something more of your own costumisation that stands out

also as one more improvement we can add the ability to download the same thing aswell ( the seleceted ep - it's there in consumet for vid src and gogo and more )

these things ig can be implemented in the kdrama web app aswell

**Comment by gneiru** [comment]
For download issue see #222

**Comment by gneiru** [comment]
Customized player not planned for now. Thanks
