### ISSUE TITLE
Anilist Redirect URI

### ISSUE THREAD

**Issue by skgupta507** [gneiru/anirohi#220]
Hey @gneiru can u  help me with the sample of the redirect uri that is used in this project.
cause i tried some redirect url but they are not working for me. i have mentioned the URIs i used.

https://xanirohi.vercel.app/api/auth/callback/AniListProvider
https://xanirohi.vercel.app/callback

these both dosent work for me
is there any other format for this project.

**Comment by gneiru** [comment]
> Hey @gneiru can u  help me with the sample of the redirect uri that is used in this project.
> 
> cause i tried some redirect url but they are not working for me. i have mentioned the URIs i used.
> 
> 
> 
> https://xanirohi.vercel.app/api/auth/callback/AniListProvider
> 
> https://xanirohi.vercel.app/callback
> 
> 
> 
> these both dosent work for me
> 
> is there any other format for this project.

Try https://xanirohi.vercel.app/api/auth/callback/anilist

**Comment by skgupta507** [comment]
i used that one and now it shows like this

![image](https://github.com/gneiru/anirohi/assets/131786207/99f075c3-4b47-475c-9155-137ae98b647b)

**Comment by skgupta507** [comment]
[logs_result (2).json](https://github.com/gneiru/anirohi/files/15346733/logs_result.2.json)

the logs of the error from vercel it says something about relation not found.

**Comment by gneiru** [comment]
I think you havent setup your auth db tables

**Comment by gneiru** [comment]
Try running `pnpm db:push`

**Comment by skgupta507** [comment]
> Try running `pnpm db:push` locally

what about vercel case i dont have to running locally it directly deployed to vercel
