### ISSUE TITLE
watch page error

### ISSUE THREAD

**Issue by skgupta507** [gneiru/anirohi#221]
Hi @gneiru i deployed the Anirohi project on vercel adding all the variables. but iam getting this error . when i click on the watch now button. screenshot attached.
![image](https://github.com/gneiru/anirohi/assets/131786207/bda6e8d5-be67-4f20-bc03-3df5c70e2d37)

the homepage seems to work properly but not the watchpage. iam using the api u povided in the project

**Comment by gneiru** [comment]
> Hi @gneiru i deployed the Anirohi project on vercel adding all the variables. but iam getting this error . when i click on the watch now button. screenshot attached.
> 
> ![image](https://github.com/gneiru/anirohi/assets/131786207/bda6e8d5-be67-4f20-bc03-3df5c70e2d37)
> 
> 
> 
> the homepage seems to work properly but not the watchpage. iam using the api u povided in the project

Is there any logs in vercel? Could you check the logs at the same time of the error

**Comment by skgupta507** [comment]
here`s the vercel log


error: relation "anirohi_anime" does not exist
    at /var/task/.next/server/chunks/897.js:9:28987
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (/var/task/.next/server/app/(pages)/anime/[slug]/page.js:1:9297)
    at async q (/var/task/.next/server/app/(pages)/anime/[slug]/page.js:1:7167) {
  length: 112,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '13',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1449',
  routine: 'parserOpenTable',
  digest: '2714756602'
}

**Comment by skgupta507** [comment]
i have added the vercel log as json file
pls look into it and help me on this matter

**Comment by capexnoelrohi** [comment]
It is related to your database schema, I'm pretty sure the tables declared in schema are not yet pushed in your database.

**Comment by skgupta507** [comment]
thanks @capexnoelrohi @gneiru the watchpage works fine now. 
thanks for the guidance.
